### PR TITLE
Add Timer and Consumer Entrypoints

### PR DESCRIPTION
**Pull request by ofmendi**

### CODE REVIEW

**Comment by zsiciarz** [comment]
Thanks a lot for the contribution! You might want to update the docstring for `PrometheusMetrics` as well, to include newly added metrics.

**Comment by ofmendi** [comment]
Your welcome. Thank you for your feedbacks.

**Review by piterma98 — APPROVED** [review]

**Comment by the01** [comment]
Hello,

Any timeline on landing this pull request?

**Comment by zsiciarz** [comment]
Thanks, merged! I've allowed myself to slightly alter metric names for `Consumer` in #29 to more accurately reflect entrypoint type.

**Pull request merged**
